// Profile
export const ADD_PROFILE = 'PROFILE/ADD_PROFILE'
export const REMOVE_PROFILE = 'PROFILE/REMOVE_PROFILE'

// UsersData
export const ADD_USERSDATA = 'USERS/ADD_USERSDATA'
export const REMOVE_USERSDATA = 'USERS/REMOVE_USERSDATA'
export const UPDATE_USERSDATA = 'USERS/UPDATE_USERSDATA'